export {default as Form} from "./Form/Form"
export {default as MainImage} from "./MainImage/MainImage"
export {default as Input} from "./InputForm/InputForm"
export {default as SelectForm} from "./SelectForm/SelectForm"
export {default as ActivateAccountForm} from "./ActivateAccountForm/ActivateAccountForm"
